### ISSUE TITLE
rosbag file for deployment

### ISSUE THREAD

**Issue by james-yoo** [PrieureDeSion/drive-any-robot#8]
Hi @PrieureDeSion,
Is it enough to prepare image and odometry topic in rosbag file? And is the accuracy of the odometry an important factor in graph generation?

**Comment by robodhruv** [comment]
Hi @james-yoo ,
Yes, that is all the information you should need in the rosbag! We did not find the odometry accuracy to be too important and used all available odometry in our public datasets out of the box -- this includes odometry from lidar, wheel encoders, VIO etc. If you have an estimate of the accuracy of odometry that is very poor, can you share it? My expectation is anything under 2-5% should not be a problem at all.

**Comment by james-yoo** [comment]
Hi @PrieureDeSion,
Sometimes it will be needed to travel hundreds of meters to kilometers for logging data. So, the accumulated distance error will be very large, which will cause problems in generating the graph. In this case, do I have to use precise positioning system (e.g. RTK, LiDAR SLAM, etc) to correct bias in odometry?

**Comment by robodhruv** [comment]
I don't think that should be too big of a problem because the odometry estimates are only used to obtain distance labels on the order of 20-40 time steps (say 10 seconds into the future). This relates closely to how the high-level planning is set up -- we only use _nearby_ pairs of states to label positives in training and train the policy on these positives. I don't think long-range drifts will be a problem as long as you have relatively good local odometry.

**Comment by james-yoo** [comment]
Thanks for your detailed explanation.
